import type { Metadata } from "next";
import "./globals.css";
import NavigationBarr from "@/components/NavigationBarr";
import Image from "next/image";
import tree from "../public/tree.jpg";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <NavigationBarr />
        <Image 
      src={tree}
      alt="img"
      className="w-full"
    />
        {children}
      </body>
    </html>
  );
}
